name: Create an issue for tracking meeting
on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * WED'
permissions:
  contents: read
  issues: write

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Meeting Issue
        id: create-issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/community-meeting-update.md
      - run: 'echo Created ${{ steps.create-issue.outputs.url }}'
        
